# Generated by Django 5.0 on 2023-12-20 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_produto_quantidade_estoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='quantidade_estoque',
        ),
    ]
