# Generated by Django 4.2.4 on 2024-01-16 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_produto_quantidade_estoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceAlmoxarifado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SceMovimentacaoEstoque',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('almoxarifado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scealmoxarifado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='SceTipoMovimentacaoEstoque',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('operacao', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SftFormaPagamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SftPedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empresa')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sftformapagamento')),
            ],
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='descricao',
            new_name='descricao_completa',
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao_resumida',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SftVendaItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sftpedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.produto')),
            ],
        ),
        migrations.CreateModel(
            name='SceSaldoEstoque',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade_estoque', models.IntegerField()),
                ('custo_produto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('almoxarifado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scealmoxarifado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empresa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.produto')),
            ],
        ),
        migrations.CreateModel(
            name='SceMovimentacaoEstoqueItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('movimentacao_estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scemovimentacaoestoque')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.produto')),
            ],
        ),
        migrations.AddField(
            model_name='scemovimentacaoestoque',
            name='tipo_movimentacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scetipomovimentacaoestoque'),
        ),
    ]
