export const ALMOXARIFADO_LIST_REQUEST = 'ALMOXARIFADO_LIST_REQUEST'
export const ALMOXARIFADO_LIST_SUCCESS = 'ALMOXARIFADO_LIST_SUCCESS'
export const ALMOXARIFADO_LIST_FAIL = 'ALMOXARIFADO_LIST_FAIL'

export const ALMOXARIFADO_DETAILS_REQUEST = 'ALMOXARIFADO_DETAILS_REQUEST'
export const ALMOXARIFADO_DETAILS_SUCCESS = 'ALMOXARIFADO_DETAILS_SUCCESS'
export const ALMOXARIFADO_DETAILS_FAIL = 'ALMOXARIFADO_DETAILS_FAIL'

export const ALMOXARIFADO_CREATE_REQUEST = 'ALMOXARIFADO_CREATE_REQUEST'
export const ALMOXARIFADO_CREATE_SUCCESS = 'ALMOXARIFADO_CREATE_SUCCESS'
export const ALMOXARIFADO_CREATE_FAIL = 'ALMOXARIFADO_CREATE_FAIL'
export const ALMOXARIFADO_CREATE_RESET = 'ALMOXARIFADO_CREATE_RESET'

export const ALMOXARIFADO_UPDATE_REQUEST = 'ALMOXARIFADO_UPDATE_REQUEST'
export const ALMOXARIFADO_UPDATE_SUCCESS = 'ALMOXARIFADO_UPDATE_SUCCESS'
export const ALMOXARIFADO_UPDATE_FAIL = 'ALMOXARIFADO_UPDATE_FAIL'
export const ALMOXARIFADO_UPDATE_RESET = 'ALMOXARIFADO_UPDATE_RESET'

export const ALMOXARIFADO_DELETE_REQUEST = 'ALMOXARIFADO_DELETE_REQUEST'
export const ALMOXARIFADO_DELETE_SUCCESS = 'ALMOXARIFADO_DELETE_SUCCESS'
export const ALMOXARIFADO_DELETE_FAIL = 'ALMOXARIFADO_DELETE_FAIL'
export const ALMOXARIFADO_DELETE_RESET = 'ALMOXARIFADO_DELETE_RESET'

