export const EMPRESA_LIST_REQUEST = 'EMPRESA_LIST_REQUEST'
export const EMPRESA_LIST_SUCCESS = 'EMPRESA_LIST_SUCCESS'
export const EMPRESA_LIST_FAIL = 'EMPRESA_LIST_FAIL'

export const EMPRESA_DETAILS_REQUEST = 'EMPRESA_DETAILS_REQUEST'
export const EMPRESA_DETAILS_SUCCESS = 'EMPRESA_DETAILS_SUCCESS'
export const EMPRESA_DETAILS_FAIL = 'EMPRESA_DETAILS_FAIL'

export const EMPRESA_CREATE_REQUEST = 'EMPRESA_CREATE_REQUEST'
export const EMPRESA_CREATE_SUCCESS = 'EMPRESA_CREATE_SUCCESS'
export const EMPRESA_CREATE_FAIL = 'EMPRESA_CREATE_FAIL'
export const EMPRESA_CREATE_RESET = 'EMPRESA_CREATE_RESET'

export const EMPRESA_UPDATE_REQUEST = 'EMPRESA_UPDATE_REQUEST'
export const EMPRESA_UPDATE_SUCCESS = 'EMPRESA_UPDATE_SUCCESS'
export const EMPRESA_UPDATE_FAIL = 'EMPRESA_UPDATE_FAIL'
export const EMPRESA_UPDATE_RESET = 'EMPRESA_UPDATE_RESET'

export const EMPRESA_DELETE_REQUEST = 'EMPRESA_DELETE_REQUEST'
export const EMPRESA_DELETE_SUCCESS = 'EMPRESA_DELETE_SUCCESS'
export const EMPRESA_DELETE_FAIL = 'EMPRESA_DELETE_FAIL'
export const EMPRESA_DELETE_RESET = 'EMPRESA_DELETE_RESET'
