export const PRODUTO_LIST_REQUEST = 'PRODUTO_LIST_REQUEST'
export const PRODUTO_LIST_SUCCESS = 'PRODUTO_LIST_SUCCESS'
export const PRODUTO_LIST_FAIL = 'PRODUTO_LIST_FAIL'

export const PRODUTO_DETAILS_REQUEST = 'PRODUTO_DETAILS_REQUEST'
export const PRODUTO_DETAILS_SUCCESS = 'PRODUTO_DETAILS_SUCCESS'
export const PRODUTO_DETAILS_FAIL = 'PRODUTO_DETAILS_FAIL'

export const PRODUTO_CREATE_REQUEST = 'PRODUTO_CREATE_REQUEST'
export const PRODUTO_CREATE_SUCCESS = 'PRODUTO_CREATE_SUCCESS'
export const PRODUTO_CREATE_FAIL = 'PRODUTO_CREATE_FAIL'
export const PRODUTO_CREATE_RESET = 'PRODUTO_CREATE_RESET'

export const PRODUTO_UPDATE_REQUEST = 'PRODUTO_UPDATE_REQUEST'
export const PRODUTO_UPDATE_SUCCESS = 'PRODUTO_UPDATE_SUCCESS'
export const PRODUTO_UPDATE_FAIL = 'PRODUTO_UPDATE_FAIL'
export const PRODUTO_UPDATE_RESET = 'PRODUTO_UPDATE_RESET'

export const PRODUTO_DELETE_REQUEST = 'PRODUTO_DELETE_REQUEST'
export const PRODUTO_DELETE_SUCCESS = 'PRODUTO_DELETE_SUCCESS'
export const PRODUTO_DELETE_FAIL = 'PRODUTO_DELETE_FAIL'
export const PRODUTO_DELETE_RESET = 'PRODUTO_DELETE_RESET'

