export const SUBCLASSE_PRODUTO_LIST_REQUEST = 'SUBCLASSE_PRODUTO_LIST_REQUEST'
export const SUBCLASSE_PRODUTO_LIST_SUCCESS = 'SUBCLASSE_PRODUTO_LIST_SUCCESS'
export const SUBCLASSE_PRODUTO_LIST_FAIL = 'SUBCLASSE_PRODUTO_LIST_FAIL'

export const SUBCLASSE_PRODUTO_DETAILS_REQUEST = 'SUBCLASSE_PRODUTO_DETAILS_REQUEST'
export const SUBCLASSE_PRODUTO_DETAILS_SUCCESS = 'SUBCLASSE_PRODUTO_DETAILS_SUCCESS'
export const SUBCLASSE_PRODUTO_DETAILS_FAIL = 'SUBCLASSE_PRODUTO_DETAILS_FAIL'

export const SUBCLASSE_PRODUTO_CREATE_REQUEST = 'SUBCLASSE_PRODUTO_CREATE_REQUEST'
export const SUBCLASSE_PRODUTO_CREATE_SUCCESS = 'SUBCLASSE_PRODUTO_CREATE_SUCCESS'
export const SUBCLASSE_PRODUTO_CREATE_FAIL = 'SUBCLASSE_PRODUTO_CREATE_FAIL'
export const SUBCLASSE_PRODUTO_CREATE_RESET = 'SUBCLASSE_PRODUTO_CREATE_RESET'

export const SUBCLASSE_PRODUTO_UPDATE_REQUEST = 'SUBCLASSE_PRODUTO_UPDATE_REQUEST'
export const SUBCLASSE_PRODUTO_UPDATE_SUCCESS = 'SUBCLASSE_PRODUTO_UPDATE_SUCCESS'
export const SUBCLASSE_PRODUTO_UPDATE_FAIL = 'SUBCLASSE_PRODUTO_UPDATE_FAIL'
export const SUBCLASSE_PRODUTO_UPDATE_RESET = 'SUBCLASSE_PRODUTO_UPDATE_RESET'

export const SUBCLASSE_PRODUTO_DELETE_REQUEST = 'SUBCLASSE_PRODUTO_DELETE_REQUEST'
export const SUBCLASSE_PRODUTO_DELETE_SUCCESS = 'SUBCLASSE_PRODUTO_DELETE_SUCCESS'
export const SUBCLASSE_PRODUTO_DELETE_FAIL = 'SUBCLASSE_PRODUTO_DELETE_FAIL'
export const SUBCLASSE_PRODUTO_DELETE_RESET = 'SUBCLASSE_PRODUTO_DELETE_RESET'

