export const TIPO_PRODUTO_LIST_REQUEST = "TIPO_PRODUTO_LIST_REQUEST";
export const TIPO_PRODUTO_LIST_SUCCESS = "TIPO_PRODUTO_LIST_SUCCESS";
export const TIPO_PRODUTO_LIST_FAIL = "TIPO_PRODUTO_LIST_FAIL";

export const TIPO_PRODUTO_DETAILS_REQUEST = "TIPO_PRODUTO_DETAILS_REQUEST";
export const TIPO_PRODUTO_DETAILS_SUCCESS = "TIPO_PRODUTO_DETAILS_SUCCESS";
export const TIPO_PRODUTO_DETAILS_FAIL = "TIPO_PRODUTO_DETAILS_FAIL";

export const TIPO_PRODUTO_CREATE_REQUEST = "TIPO_PRODUTO_CREATE_REQUEST";
export const TIPO_PRODUTO_CREATE_SUCCESS = "TIPO_PRODUTO_CREATE_SUCCESS";
export const TIPO_PRODUTO_CREATE_FAIL = "TIPO_PRODUTO_CREATE_FAIL";
export const TIPO_PRODUTO_CREATE_RESET = "TIPO_PRODUTO_CREATE_RESET";

export const TIPO_PRODUTO_UPDATE_REQUEST = "TIPO_PRODUTO_UPDATE_REQUEST";
export const TIPO_PRODUTO_UPDATE_SUCCESS = "TIPO_PRODUTO_UPDATE_SUCCESS";
export const TIPO_PRODUTO_UPDATE_FAIL = "TIPO_PRODUTO_UPDATE_FAIL";
export const TIPO_PRODUTO_UPDATE_RESET = "TIPO_PRODUTO_UPDATE_RESET";

export const TIPO_PRODUTO_DELETE_REQUEST = "TIPO_PRODUTO_DELETE_REQUEST";
export const TIPO_PRODUTO_DELETE_SUCCESS = "TIPO_PRODUTO_DELETE_SUCCESS";
export const TIPO_PRODUTO_DELETE_FAIL = "TIPO_PRODUTO_DELETE_FAIL";
export const TIPO_PRODUTO_DELETE_RESET = "TIPO_PRODUTO_DELETE_RESET";

